import { reactive } from "vue"
const baseUrl = "src/storage/pic/"

export const clothes = reactive([
    {
        id: 0,
        hashKey: "diLunZhiWu",
        name: "涤纶织物",
        unit: "kg",
        pic: baseUrl + "Clothing.png",
        number: 0,
        carbon: 25.7,
    },
    {
        id: 1,
        hashKey: "chunMianTXv",
        name: "纯棉T恤",
        unit: "件",
        pic: baseUrl + "Tee.png",
        number: 0,
        carbon: 7.0,
    },
    {
        id: 2,
        hashKey: "xiYiYe",
        name: "洗衣液",
        unit: "L",
        pic: baseUrl + "shampoo.png",
        number: 0,
        carbon: 0.8,
    },
])

export const food = reactive([
    {
        id: 3,
        hashKey: "liangShiXiaoFei",
        name: "粮食消费",
        unit: "kg",
        pic: baseUrl + "grain.png",
        number: 0,
        carbon: 8.0,
    },
    {
        id: 4,
        hashKey: "yangRou",
        name: "羊肉",
        unit: "kg",
        pic: baseUrl + "meet.png",
        number: 0,
        carbon: 39.2,
    },
    {
        id: 5,
        hashKey: "niuRou",
        name: "牛肉",
        unit: "kg",
        pic: baseUrl + "beef.png",
        number: 0,
        carbon: 27.0,
    },
    {
        id: 6,
        hashKey: "zhuRou",
        name: "猪肉",
        unit: "kg",
        pic: baseUrl + "Fatmeat.png",
        number: 0,
        carbon: 12.1,
    },
    {
        id: 7,
        hashKey: "zhaJi",
        name: "炸鸡",
        unit: "kg",
        pic: baseUrl + "chicken.png",
        number: 0,
        carbon: 1.8,
    },
    {
        id: 8,
        hashKey: "jiDan",
        name: "鸡蛋",
        unit: "kg",
        pic: baseUrl + "egg.png",
        number: 0,
        carbon: 4.8,
    },
    {
        id: 9,
        hashKey: "tuDou",
        name: "土豆",
        unit: "kg",
        pic: baseUrl + "potato.png",
        number: 0,
        carbon: 2.9,
    },
    {
        id: 10,
        hashKey: "miFan",
        name: "米饭",
        unit: "kg",
        pic: baseUrl + "rice.png",
        number: 0,
        carbon: 2.7,
    },
    {
        id: 11,
        hashKey: "huaSheng",
        name: "花生",
        unit: "kg",
        pic: baseUrl + "peanut.png",
        number: 0,
        carbon: 2.5,
    },
    {
        id: 12,
        hashKey: "suanNai",
        name: "酸奶",
        unit: "kg",
        pic: baseUrl + "yogurt.png",
        number: 0,
        carbon: 2.2,
    },
    {
        id: 13,
        hashKey: "xiLanHua",
        name: "西兰花",
        unit: "kg",
        pic: baseUrl + "Cauliflower.png",
        number: 0,
        carbon: 2.0,
    },
    {
        id: 14,
        hashKey: "douFu",
        name: "豆腐",
        unit: "kg",
        pic: baseUrl + "tofu.png",
        number: 0,
        carbon: 2.9,
    },
    {
        id: 15,
        hashKey: "niuNai",
        name: "牛奶",
        unit: "kg",
        pic: baseUrl + "milk.png",
        number: 0,
        carbon: 1.9,
    },
    {
        id: 16,
        hashKey: "xiHongShi",
        name: "西红柿",
        unit: "kg",
        pic: baseUrl + "tomato.png",
        number: 0,
        carbon: 1.1,
    },
    {
        id: 17,
        hashKey: "bianDou",
        name: "扁豆",
        unit: "kg",
        pic: baseUrl + "Beans.png",
        number: 0,
        carbon: 0.9,
    }
])

export const house = reactive([
    {
        id: 18,
        hashKey: "mei",
        name: "煤",
        unit: "吨",
        pic: baseUrl + "coal.png",
        number: 0,
        carbon: 1970.0,
    },
    {
        id: 19,
        hashKey: "yongDian",
        name: "用电",
        unit: "度",
        pic: baseUrl + "lamp.png",
        number: 0,
        carbon: 1.0,
    },
    {
        id: 20,
        hashKey: "yongShui",
        name: "用水",
        unit: "立方米",
        pic: baseUrl + "water.png",
        number: 0,
        carbon: 0.9,
    },
    {
        id: 21,
        hashKey: "meiQi",
        name: "煤气",
        unit: "立方米",
        pic: baseUrl + "gas.png",
        number: 0,
        carbon: 0.7,
    },
    {
        id: 22,
        hashKey: "tianRanQi",
        name: "天然气",
        unit: "立方米",
        pic: baseUrl + "naturalgas.png",
        number: 0,
        carbon: 2.2,
    },
    {
        id: 23,
        hashKey: "jiZhongGongNuan",
        name: "集中供暖",
        unit: "平方*天",
        pic: baseUrl + "Heating.png",
        number: 0,
        carbon: 0.1,
    },
    {
        id: 24,
        hashKey: "fengWoMei",
        name: "蜂窝煤",
        unit: "块",
        pic: baseUrl + "Honeycomb.png",
        number: 0,
        carbon: 3.3,
    },
    {
        id: 25,
        hashKey: "yeHuaQi",
        name: "液化气",
        unit: "立方米",
        pic: baseUrl + "liquid.png",
        number: 0,
        carbon: 5.5,
    },
])

export const journey = reactive([
    {
        id: 26,
        hashKey: "feiJi",
        name: "飞机",
        unit: "公里",
        pic: baseUrl + "air.png",
        number: 0,
        carbon: 0.3,
    },
    {
        id: 27,
        hashKey: "huoChe",
        name: "火车",
        unit: "公里",
        pic: baseUrl + "train.png",
        number: 0,
        carbon: 0.01,
    },
    {
        id: 28,
        hashKey: "lunChuan",
        name: "轮船",
        unit: "公里",
        pic: baseUrl + "ship.png",
        number: 0,
        carbon: 0.01,
    },
    {
        id: 29,
        hashKey: "diTie",
        name: "地铁",
        unit: "站",
        pic: baseUrl + "subway.png",
        number: 0,
        carbon: 0.1,
    },
    {
        id: 30,
        hashKey: "gongHongQiChe",
        name: "公共汽车",
        unit: "公里",
        pic: baseUrl + "bus.png",
        number: 0,
        carbon: 0.01,
    },
    {
        id: 31,
        hashKey: "gaoHaoYouXiaoQiChe",
        name: "高耗油小汽车",
        unit: "公里",
        pic: baseUrl + "car.png",
        number: 0,
        carbon: 0.4,
    },
    {
        id: 32,
        hashKey: "zhongHaoYouXiaoQiChe",
        name: "中耗油小汽车",
        unit: "公里",
        pic: baseUrl + "Mediumcar.png",
        number: 0,
        carbon: 0.3,
    },
    {
        id: 33,
        hashKey: "diHaoYouXiaoQiChe",
        name: "低耗油小汽车",
        unit: "公里",
        pic: baseUrl + "lowcar.png",
        number: 0,
        carbon: 0.3,
    }
])

export const use = reactive([
    {
        id: 34,
        hashKey: "zhiZhiPing",
        name: "纸制品",
        unit: "kg",
        pic: baseUrl + "coffee.png",
        number: 0,
        carbon: 3.5,
    },
    {
        id: 35,
        hashKey: "suLiaoDai",
        name: "塑料袋",
        unit: "个",
        pic: baseUrl + "plastic.png",
        number: 0,
        carbon: 0.0001,
    },
    {
        id: 36,
        hashKey: "yiCiXingKuaiZi",
        name: "一次性筷子",
        unit: "块",
        pic: baseUrl + "chopsticks.png",
        number: 0,
        carbon: 0.0001,
    },
    {
        id: 36,
        hashKey: "xiFaShui",
        name: "洗发水",
        unit: "瓶",
        pic: baseUrl + "sham.png",
        number: 0,
        carbon: 0.0001,
    },
    {
        id: 37,
        hashKey: "meiGui",
        name: "玫瑰",
        unit: "支",
        pic: baseUrl + "rose.png",
        number: 0,
        carbon: 0.0001,
    },
    {
        id: 38,
        hashKey: "chengShiLaJi",
        name: "城市垃圾",
        unit: "kg",
        pic: baseUrl + "building.png",
        number: 0,
        carbon: 2.1,
    }
])

const data = [
    {
        id: 0,
        hashKey: "diLunZhiWu",
        name: "涤纶织物",
        unit: "kg",
        carbon: 25.7,
    },
    {
        id: 1,
        hashKey: "chunMianTXv",
        name: "纯棉T恤",
        unit: "件",
        carbon: 7.0,
    },
    {
        id: 2,
        hashKey: "xiYiYe",
        name: "洗衣液",
        unit: "L",
        carbon: 0.8,
    },
    {
        id: 3,
        hashKey: "liangShiXiaoFei",
        name: "粮食消费",
        unit: "kg",
        carbon: 8.0,
    },
    {
        id: 4,
        hashKey: "yangRou",
        name: "羊肉",
        unit: "kg",
        carbon: 39.2,
    },
    {
        id: 5,
        hashKey: "niuRou",
        name: "牛肉",
        unit: "kg",
        carbon: 27.0,
    },
    {
        id: 6,
        hashKey: "zhuRou",
        name: "猪肉",
        unit: "kg",
        carbon: 12.1,
    },
    {
        id: 7,
        hashKey: "zhaJi",
        name: "炸鸡",
        unit: "kg",
        carbon: 1.8,
    },
    {
        id: 8,
        hashKey: "jiDan",
        name: "鸡蛋",
        unit: "kg",
        carbon: 4.8,
    },
    {
        id: 9,
        hashKey: "tuDou",
        name: "土豆",
        unit: "kg",
        carbon: 2.9,
    },
    {
        id: 10,
        hashKey: "miFan",
        name: "米饭",
        unit: "kg",
        carbon: 2.7,
    },
    {
        id: 11,
        hashKey: "huaSheng",
        name: "花生",
        unit: "kg",
        carbon: 2.5,
    },
    {
        id: 12,
        hashKey: "suanNai",
        name: "酸奶",
        unit: "kg",
        carbon: 2.2,
    },
    {
        id: 13,
        hashKey: "xiLanHua",
        name: "西兰花",
        unit: "kg",
        carbon: 2.0,
    },
    {
        id: 14,
        hashKey: "douFu",
        name: "豆腐",
        unit: "kg",
        carbon: 2.9,
    },
    {
        id: 15,
        hashKey: "niuNai",
        name: "牛奶",
        unit: "kg",
        carbon: 1.9,
    },
    {
        id: 16,
        hashKey: "xiHongShi",
        name: "西红柿",
        unit: "kg",
        carbon: 1.1,
    },
    {
        id: 17,
        hashKey: "bianDou",
        name: "扁豆",
        unit: "kg",
        carbon: 0.9,
    },
    {
        id: 18,
        hashKey: "mei",
        name: "煤",
        unit: "吨",
        carbon: 1970.0,
    },
    {
        id: 19,
        hashKey: "yongDian",
        name: "用电",
        unit: "度",
        carbon: 1.0,
    },
    {
        id: 20,
        hashKey: "yongShui",
        name: "用水",
        unit: "立方米",
        carbon: 0.9,
    },
    {
        id: 21,
        hashKey: "meiQi",
        name: "煤气",
        unit: "立方米",
        carbon: 0.7,
    },
    {
        id: 22,
        hashKey: "tianRanQi",
        name: "天然气",
        unit: "立方米",
        carbon: 2.2,
    },
    {
        id: 23,
        hashKey: "jiZhongGongNuan",
        name: "集中供暖",
        unit: "平方*天",
        carbon: 0.1,
    },
    {
        id: 24,
        hashKey: "fengWoMei",
        name: "蜂窝煤",
        unit: "块",
        carbon: 3.3,
    },
    {
        id: 25,
        hashKey: "yeHuaQi",
        name: "液化气",
        unit: "立方米",
        carbon: 5.5,
    },
    {
        id: 26,
        hashKey: "feiJi",
        name: "飞机",
        unit: "公里",
        carbon: 0.3,
    },
    {
        id: 27,
        hashKey: "huoChe",
        name: "火车",
        unit: "公里",
        carbon: 0.01,
    },
    {
        id: 28,
        hashKey: "lunChuan",
        name: "轮船",
        unit: "公里",
        carbon: 0.01,
    },
    {
        id: 29,
        hashKey: "diTie",
        name: "地铁",
        unit: "站",
        carbon: 0.1,
    },
    {
        id: 30,
        hashKey: "gongHongQiChe",
        name: "公共汽车",
        unit: "公里",
        carbon: 0.01,
    },
    {
        id: 31,
        hashKey: "gaoHaoYouXiaoQiChe",
        name: "高耗油小汽车",
        unit: "公里",
        carbon: 0.4,
    },
    {
        id: 32,
        hashKey: "zhongHaoYouXiaoQiChe",
        name: "中耗油小汽车",
        unit: "公里",
        carbon: 0.3,
    },
    {
        id: 33,
        hashKey: "diHaoYouXiaoQiChe",
        name: "低耗油小汽车",
        unit: "公里",
        carbon: 0.3,
    },
    {
        id: 34,
        hashKey: "zhiZhiPing",
        name: "纸制品",
        unit: "kg",
        carbon: 3.5,
    },
    {
        id: 35,
        hashKey: "suLiaoDai",
        name: "塑料袋",
        unit: "个",
        carbon: 0.0001,
    },
    {
        id: 36,
        hashKey: "yiCiXingKuaiZi",
        name: "一次性筷子",
        unit: "块",
        carbon: 0.0001,
    },
    {
        id: 36,
        hashKey: "xiFaShui",
        name: "洗发水",
        unit: "瓶",
        carbon: 0.0001,
    },
    {
        id: 37,
        hashKey: "meiGui",
        name: "玫瑰",
        unit: "支",
        carbon: 0.0001,
    },
    {
        id: 38,
        hashKey: "chengShiLaJi",
        name: "城市垃圾==",
        unit: "kg",
        carbon: 2.1,
    }
]