const data = {
    //衣食两板块
    "diLunZhiWu": 25.7,
    "chunMianTXv": 7.0,
    "xiYiYe": 0.8,
    "liangShiXiaoFei": 8.0,
    
    "yangRou": 39.2,
    "niuRou": 27.0,
    "zhuRou": 12.1,
    "zhaJi": 1.8,
    "jiDan": 4.8,
    "tuDou": 2.9,
    "miFan": 2.7,
    "huaSheng": 2.5,
    "suanNai": 2.2,
    "xiLanHua": 2.0,
    "douFu": 2.0,
    "niuNai": 1.9,
    "xiHongShi": 1.1,
    "bianDou": 0.9,

    "mei": 1970.0,
    "yongDian": 1.0,
    "yongShui": 0.9,
    "meiQi": 0.7,
    "tianRanQi": 2.2,
    "jiZhongGongNuan": 0.1,
    "fengWoMei": 3.3,
    "yeHuaQi": 5.5,

    "feiJi": 0.3,
    "huoChe": 0.01,
    "lunChuan": 0.01,
    "diTie": 0.1,
    "gongGongQiChe": 0.01,
    "gaoHaoYouXiaoQiChe": 0.4,
    "zhongHaoYouXiaoQiChe": 0.3,
    "diHaoYouXiaoQiChe": 0.3,

    //用板块
    "zhiZhiPing": 3.5,
    "suLiaoDai": 0.0,
    "yiCiXingKuaiZi": 0.0,
    "xiFaShui": 0.0,
    "meiGui": 0.2,
    "chengShiLaJi": 2.1,
}